### ISSUE TITLE
Problem with Example "Execute Multiple Commands with a Single Channel.vi"

### ISSUE THREAD

**Issue by samcgill29** [fieldrndservices/libssh2-labview#30] opened 2020-12-26 23:55 UTC
I'm following up on a recently closed issue with similar title to the current one.

I am using the example on Windows 10 with LabVIEW 2019f2 release. I can "execute multiple commands with multiple channels" and it works fine.  However, I run into issues whenever I use the "Shell" channel vi in the "multiple commands with single channel" example.  The problem is that, similar to the prior issue that is now closed, when I send a command I only receive the sent command echoed back to me when I read the response.  This is not an issue when I use the Execute shell command vi, only when I try to write and read after opening the shell-type channel.  So, for example, if I send the command, "date -u +%s" what I receive back is "date -u +%s" instead of the date in elapsed seconds that I would expect to get.  Can you please help me with the solution?

**Comment by volks73** [comment] 2020-12-27 18:15
Thank you for your interest and usage of this toolkit. I am sorry to hear you are experiencing problems. Let's see what we can do together to resolve your problem.

I believe you are referring to Issue #28. Have you tried [the solution](https://user-images.githubusercontent.com/1915469/101248413-e3618b80-36ea-11eb-9e02-fa70b1167563.png) mentioned in [my comment](https://github.com/fieldrndservices/libssh2-labview/issues/28#issuecomment-739324640) in that issue, i.e. add a "[Read.vi](https://github.com/fieldrndservices/libssh2-labview/blob/main/src/Toolkit/Channel/Read%20All.vi)" before the first write?

Could you also checkout the latest version of this toolkit (git clone) and try the "[Read-Execute-Print-Loop with a Raspberry Pi](https://github.com/fieldrndservices/libssh2-labview/blob/main/src/Examples/Read-Execute-Print-Loop%20with%20a%20Raspberry%20Pi.vi)" example? Your remote SSH server does not need to be a Raspberry Pi. It can be any SSH server, but recently I have gotten a lot of requests and issues related to connecting to a Raspberry Pi from LabVIEW. Can you paste the contents of the read loop and/or take a screenshot? This example is not available in [v1.0.0](https://www.vipm.io/package/field_rnd_services_libssh2/), which is currently on [VIPM.io](https://www.vipm.io/). I need to create a new release in the near future, but it is available from GitHub.

What is the SSH server you are trying to connect to from your Windows 10 computer? Is the SSH server a CompactRIO, Raspberry Pi, Linux server, another Windows 10 computer, etc? Do you happen to know which SSH server software is running on the remote system, i.e. OpenSSH?

**Comment by samcgill29** [comment] 2020-12-28 04:57
Hi, Thank you for your response and thank you also for this library. It has been extremely useful.

Yes, I am referring to Issue #28.  I did try the solution you suggested to add a "Read.vi" before the first write. That was very much needed because even though I am not working with a Raspberry Pi, my Linux instance (running Ubuntu 20.04 LTS) also did respond with a login message that needed to be read out before issuing commands.

Even though I did read the login message before attempting to write a command, I still am faced with the problem that I only receive my own commands echoed back to me and no other response.

At your suggestion, I cloned the github repo and tried using the "Read-Execute-Print-Loop with a Raspberry Pi" example. The example still only returns my commands back to me with no other response.  For example, I tried some simple commands like pwd, whoami, date, ls, but I only ever just get the command echoed back to me with nothing else.  I can issue a few commands -- about 5 or 6 and then the example VI hangs.  Turning on highlight execution shows a read.vi call that is running but never returns.  When this happens, I am not able to close the vi or abort it. I am only able to recover by ending LabVIEW using the Windows Task Manager "end task" option.  I have never been able to quit the example vi normally.

My Ubuntu server is running OpenSSH.  Please let me know if I can help with any other information.

**Comment by samcgill29** [comment] 2020-12-28 05:12
![Img1](https://user-images.githubusercontent.com/58127179/103190919-e4787980-48a0-11eb-8c0c-490e438d1a22.PNG)

Here is an image of the results I get when using the other example "Execute Multiple Commands with a Single Channel to a Raspberry Pi" which otherwise works fine (no hangs, also this is the version I just cloned from the Github repo) except that, as you can see in the image, the response just repeats the entered commands.  The login message is read out fine, but I don't otherwise seem to be able to get anything else back from the linux server.

**Comment by samcgill29** [comment] 2020-12-28 05:18
Perhaps it is also useful to mention that I can send multiple commands with multiple channels, as in one of the other examples in the library.  This works fine except that I need to close and then reopen a channel for each command. That example uses the execute.vi rather than shell.vi.  I am doing this as a workaround for the moment, but I would benefit from the ability to stream multiple commands using the shell.vi capability.

**Comment by volks73** [comment] 2020-12-28 18:46
Also mentioned in one of [my comments](https://github.com/fieldrndservices/libssh2-labview/issues/28#issuecomment-738086503) in #28, maybe try adding the "Flush.vi" after you send the command with the "Write.vi". I believe closing a channel forces a write of all the entire buffer and I think that is also the purpose of the Flush.vi.

I do wonder if the OpenSSH server has some "echo" feature that is enabled for a Shell channel. We would need to review the OpenSSH server documentation. Do you have a second OpenSSH server that you can try?

**Comment by volks73** [comment] 2020-12-28 20:03
I will try to setup an Ubuntu 20.04 instances to attempt to recreate the issue, but I cannot commit to a timeline.

>...I can issue a few commands -- about 5 or 6 and then the example VI hangs. Turning on highlight execution shows a read.vi call >that is running but never returns. When this happens, I am not able to close the vi or abort it. I am only able to recover by >ending LabVIEW using the Windows Task Manager "end task" option. I have never been able to quit the example vi normally.

I think the LabVIEW TCP Read has a very long timeout (10 minutes). The TCP handle is passed to the libssh2 and "cast" into a SSH handle, which may or may not use the same timeout. I think the Read VI is waiting for content to read and I need to update the example to send an EOF or some other signal to "wake up" the SSH/TCP connection. While this provides some direction for the stalling and lock up occurring, it does not address the lack of response from commands.

I wonder if the Bytes to Read value is too small (1024). What happens if you increase this from 1024 to some larger value?

**Comment by samcgill29** [comment] 2020-12-28 20:39
![Img2](https://user-images.githubusercontent.com/58127179/103241424-277a3180-4921-11eb-9f69-8e2127533870.PNG)

Here is an image of the modified version of the example, "Execute multiple commands with a single channel to a raspberry pi" that incorporates a flush.vi after the write.vi.  I had not tried this suggestion before. I still get a similar result, but the output did change a little with the inclusion of the flush.vi.  I also increased the maximum read bytes in this modified example. I had increased the maximum read amount previously, but it did not help with my issue.

![Img4](https://user-images.githubusercontent.com/58127179/103241619-c30ba200-4921-11eb-8e40-9a8805522789.PNG)

In the image above which utilizes the modified block diagram (includes the flush.vi) it is possible to see some additional text appear in the response 2 indicator that did not appear prior to using the flush.vi. It precedes the usual echo of the command.

![Img3](https://user-images.githubusercontent.com/58127179/103241768-39100900-4922-11eb-8eaf-18a78de1f73d.PNG)

In the image above I changed the two command response indicators to codes display in order to show any non-printing characters that may be included with the responses.  There are a lot of white space characters returned on the second response after the command echo.  I don't know if this is helpful for diagnostic purposes. 

I will browse the OpenSSH documentation to see if there is a setting for how the shell responds to commands that may fix the issue.  I have a server for testing purposes and I can alter some of the OpenSSH settings if there are any you would like me to try.

**Comment by volks73** [comment] 2020-12-29 14:18
What about a flush before the write instead of after?

**Comment by samcgill29** [comment] 2020-12-29 15:12
![Img5](https://user-images.githubusercontent.com/58127179/103293285-8ee5bf00-49bd-11eb-9490-78cbd950a79b.PNG)

Here is the code with flush.vi inserted after opening a shell and before and after write.vi

![Img6](https://user-images.githubusercontent.com/58127179/103293333-ade45100-49bd-11eb-97e6-e395d6d1105d.PNG)

The above figure shows the result of the modified code.  It seems the additional flush.vi(s) got rid of the extraneous white space characters that I observed in the former response, but otherwise no progress on the original issue.

**Comment by volks73** [comment] 2020-12-30 01:15
I was reading a little bit about the Shell channel, specifically [this page](https://api.libssh.org/stable/libssh_tutor_shell.html) about the libssh (_not_ the libssh2 library used by this toolkit, but similar enough). Note the discussion about interactive/non-interactive discussion.

The "Dump" terminal is being used in each of the snippets/examples. Maybe try a different terminal (xterm or otherwise). I wonder if the "dump" terminal is just echoing back or something.

**Comment by samcgill29** [comment] 2020-12-30 01:57
I had tried the different terminal types earlier with the library installed from VIPM. However, since I'm now using the latest library from GitHub and since the code has been modified a bit, I tried the example program just now with all the different terminal types that "Write Terminal.vi" offers.  All produce exactly the same result as the "dump" type as far as I can tell.

Thank you for the link.  I will read through it too.  I'll also keep trying some things with the library to see if I can hit on something that works. I don't think I know enough about tcp communication to be able to understand the libssh2 code itself, so I'm limited in my ability to investigate the potential issue from the underlying codebase.  BTW, if I can setup another linux host on my network, is there a different type of SSH server that you recommend trying the library with?  Other than the Raspberry Pi, what OS and SSH server combo has this LabVIEW library been tested against?  Thanks again very much for your assistance.

**Comment by volks73** [comment] 2020-12-30 02:05
>Other than the Raspberry Pi, what OS and SSH server combo has this LabVIEW library been tested against?

NI Real-Time Linux running on a couple different CompactRIO models.

>BTW, if I can setup another linux host on my network, is there a different type of SSH server that you recommend trying the library with?

OpenSSH is the most common. I don't have another recommendation, but I just thought about this. You are running Windows 10 on the host/local machine. Recent versions of Windows 10 have the OpenSSH Server also installed, or you can run the OpenSSH server through WSL. What happens if you try to connect to the local OpenSSH Server on Windows 10 through the example? I have tested the example with a similar setup on my Windows 10 machine.

**Comment by volks73** [comment] 2020-12-30 02:20
Hmm, some further digging and found [this discussion](https://forum.mikrotik.com/viewtopic.php?t=151149):

>I'm accessing device using libssh2 library from my programm and i clearly see that devices echoes everything entered back. And that's normal behavior for interactive sessions.

So, I think it is something with the configuration on the remote SSH server and/or we are missing some VI/function call to disable the interactive session echoing. This at least gives us something to research.

**Comment by volks73** [comment] 2020-12-30 02:25
Kind of a lot to unpack in this Q&A, but there might be something here: https://serverfault.com/questions/593399/what-is-the-benefit-of-not-allocating-a-terminal-in-ssh

**Comment by samcgill29** [comment] 2020-12-30 18:39
After reading some of these links, I'm beginning to wonder if what is implemented by the libssh2 code underlying shell.vi is really even meant to do what I am attempting.  I am looking mainly for a convenient way to communicate with a remote server non-interactively that doesn't require the additional overhead of opening and closing channels for each command. However, I'm left with the impression that perhaps shell.vi should be used with additional code that implements an interface for an interactive session with the remote server, such as a pseudo-terminal device within LabVIEW. I could be completely off-the-mark with this impression, I don't know.  Perhaps there is a way to implement/configure shell.vi that makes it usable for both interactive and non-interactive sessions. That still leaves as an open question what OpenSSH on Ubuntu does differently than ssh sessions on CompactRIO and Raspberry Pi, for example. Could it be that Execute.vi is exclusively for non-interactive communication and shell.vi for interactive communication?  If so, is the single channel per command paradigm of execute.vi (really the libssh2 code underlying it is what I mean) meant to discourage the apparently frowned upon idea of trying to use a non-interactive session for an interactive one?  I suppose I would be a bit disappointed if what I'm suggesting is the case since it would seem that the philosophy underlying the libssh2 code produced a library that intentionally handicapped automation of non-interactive sessions. So,, I hope I'm wrong.

**Comment by volks73** [comment] 2020-12-30 20:14
Some good news and bad news.

Good news: I am able to re-create the exact behavior you are seeing with the command being echo-ed instead of the output of the command using a Raspberry Pi and the "Read-Execute-Print-Loop with Raspberry Pi" example (I am assuming similar behavior with the "Execute Multiple Commands with a Single Channel" example. REPL VI is a little easier for debugging). I have also figured out the issue with the REPL example locking up and requiring a hard abort (Task Manager). I will try to push an update shortly once I have polished up the changes.

Bad news: while I can recreate the behavior, I still do not have a fix. I think I may have misremembered about any of these examples working. In my haste and limited testing of the examples, I may have just not noticed the "echo" in front of the output. Let's assume similar behavior on all Raspberry Pis and CompactRIOs. 

I am also approaching the same conclusion as you with regard to the interactive and non-interactive functionality, but I would like to do some more testing now that I can reproduce the behavior because I agree there must be missing something because it just seems weird to have to create and destroy channels per command.

However, creating and destroying channels does not appear to be an "expensive" or "intensive" operation within the libssh2 library and SSH in general. Creating and destroying sessions appear to be the expensive and intensive operation, which you only need to do once per connection to a remote SSH server.

**Comment by volks73** [comment] 2020-12-30 22:16
@samcgill29 Progress! This is kind of a forehead slap but also not quite a 100% fix. Add a Line Feed, a.k.a. Newline (`\n`), character to the end of each command string. It will still echo the exact command but it will also _execute_ each command. Pressing ENTER in a terminal actually prints the `\n` character on UNIX systems and the shell interprets the `\n` as the end of the command and signal to execute. We were just sending the command to the remote SSH server but never signalling the remote shell to execute the command.

Now, the echoing of the command is still a thing, but I can at least get the command to execute and change the output. For example, I get the following with my modified REPL example VI:

![Front-Panel-Capture](https://user-images.githubusercontent.com/1915469/103383857-4f54cb00-4ac2-11eb-9a22-f59ded7a6874.PNG)

when I modify the block diagram as followed:

![Block-Diagram-Capture](https://user-images.githubusercontent.com/1915469/103383879-68f61280-4ac2-11eb-8454-b8a356dd2253.PNG)

Note, I have made some other changes to this example VI to help with freezing locking, but modifying the Multiple Commands with a Single Channel example should also work. There might need to be some more parsing since the command echo is still there, but notice the "Hello World!" line without the echo.

I still need to work on the command echo but this might be something with the remote SSH server configuration, terminal configuration, etc. I don't think it is a libssh2 thing, but a terminal configuration thing that I need to research how to do through libssh2.

**Comment by samcgill29** [comment] 2020-12-30 22:44
Bravo!!  That's fantastic.  I had tried a number of different line termination characters in the example I've been using ("Execute Multiple Commands with a Single Channel") without any progress.  You can see in the image I've clipped below that adding a newline character only led to a newline character being tacked onto the response echo with no execution following.  So, there is something different between the two examples (REPL & the one I've used). I had to stop using REPL because of the lock-up issue it caused me.  Several times I couldn't even get a single command to echo before it hanged.  Once you've had an opportunity to push a new version of REPL to the repo, I will certainly try it again with the additional newline character.  The few times I did use it, I was typing commands in and hitting "enter/return" in order for the event loop to capture a value change in the command variable. Is an additional line feed character necessary or does enter/return append the wrong termination character?

![Img7](https://user-images.githubusercontent.com/58127179/103384974-701f1f80-4ac6-11eb-8b88-95b55e73b90a.PNG)

**Comment by volks73** [comment] 2020-12-31 17:20
@samcgill29 I have pushed a commit that will be of interest to you and provides a complete resolution to executing multiple commands with a single channel. In feedc6ec69e5f93242ff4fccef233b01972af52d, I provide an updated and fixed "Multiple Commands with a Single Channel using a Raspberry Pi" example that should work for your environment/system even if the remote SSH server is not a Raspberry Pi. I am in the process of updating the non-Pi version and the REPL example with the needed changes. The REPL example still needs work because I need to switch it to non-blocking mode.

The commit message of feedc6ec69e5f93242ff4fccef233b01972af52d summarizes the needed changes and issues that were at play, but to have everything in one play for future users: 

You were correct in that it would be weird if the LIBSSH2 library did not allow multiple commands with a single channel and it is/was related to interactive versus non-interactive shells. We should _not_ be requesting a pseudo-terminal (pty). We only need to request/use a Shell channel. This creates a non-interactive shell and eliminates the local echoing and display of the prompt (`pi@raspberrypi:~$`) and provides a more programmatic way of executing commands without human interaction. 

However, we still need to indicate to the non-interactive shell the different commands so it knows when to execute versus wait for more input. In other words, we need to delimit each command. This is done with the Newline character, `\n`, in UNIX. The LabVIEW EOL string constant will not work from a Windows 10 client because it will append `\r\n` (Carriage Return and Line Feed/Newline) and the UNIX shell will have issues with the `\r` character. 

Finally, the LIBSSH2 library really wants to know the size of everything ahead of time. This is kind of a security thing to avoid buffer overruns and segmentation faults in C. Networking protocols also like to know the size of things ahead of time, but in practice, we really do not know all of this ahead of time, especially across different systems. Thus, all of the Read and Write VIs want to know how many bytes to read or write ahead of time and will wait, or "block", until all of the bytes have been read. This poses a problem if the number of bytes to read or write is variable and/or not known ahead of time. For example, the login message that is displayed by the Raspberry Pi when you SSH from a terminal or PuTTY may not be the same content and therefore size the login message on another Raspberry Pi or remote SSH server (it is actually customizable by the server admin). This is further complicated because a SSH channel, TCP connection, etc. are "streams" of bytes and because of jitter and latency, complete messages and/or response may not arrive in the appropriate buffer "all at once". Partial messages are possible and common. 

So, if we do not know the size of the message ahead of time, how do we know when to stop reading or writing?

Well, the "non-blocking" examples for the LIBSSH2 library and other implementations is one possibility, but it requires an implementation similar to the REPL example instead of the nice, sequential implementation of the Multiple Command examples. A non-blocking implementation could be used, but it requires a lot more code and complexity than for an example VI. The simple implementation is to use a global timeout for the SSH session. If the timeout is reached, then we assume there is no more data to read or write. The trick is to select a timeout value large enough to account jitter and/or latency in the connection between the client and server versus appearing unresponsive or sluggish to the user. If a timeout is used, then the various size inputs to the VIs become "max size" as a fallback value. The "max size" could be set to the exact size to avoid timeouts and/or be faster. Therefore, I used the "Write Timeout" VI from the Session class and modified the Read All and Write All VIs to work with timeouts. These now have an indicator that is TRUE if a time out occurred. It is still up to the end-user to interpret the meaning of the timeout (Was the connection lost? Is there no more data? Was all of the data read?) but it makes the example work and can be used to build a more robust implementation. Generally, if a timeout is used and the Max Size is reached with a FALSE "Timed Out?" value means that the Max Size probably needs to be increased because there is more of the message to be sent, but if the data size is less than the Max Size and the "Timed Out?" is TRUE, then there is no more data to read. A subsequent VI should be used to determine the difference between a lost connection or no more data to read.

Please checkout the last revision/commit and let me know if the updated example works for your system.

**Comment by volks73** [comment] 2020-12-31 17:42
I just pushed de559836d143233920f41912c3b649b651daf211, which updates the non-Raspberry Pi example: "Execute Multiple Commands with a Single Channel". Note, the two are nearly identical except the Raspberry Pi-based example has defaults and documentation specific to Raspberry Pis as the remote SSH server. However, this updated non-Raspberry Pi example is untested (currently do not have a non-Raspberry Pi remote SSH server setup).

**Comment by volks73** [comment] 2020-12-31 18:07
The fixed REPL example is available as of 4f209a09a16ba8d40eaf61a50b670647b6552afa. I have tested this with a Raspberry Pi and it does not stall or require a hard reset (Task Manager->End Task). This also includes some other quality of life/UX improvements. I think it is actually kind of neat. I will be curious if it works with non-Pi remote SSH servers.

**Comment by samcgill29** [comment] 2021-01-02 05:57
@volks73 I can confirm that both of the updated examples, "Execute Multiple Commands with a Single Channel.vi" and REPL.vi work with my Ubuntu Server 20.04 instance.  I am not observing any command echoes and the REPL example does not hang for me anymore.  

Thank you very much!  The original issue I was having does not occur any more.  This library is a fantastic tool, and I appreciate very much the support! LabVIEW supports TCP communication on a low-level, but I don't know of any other solutions that make working with SSH this easy.

**Comment by volks73** [comment] 2021-01-02 16:10
I am glad to hear that everything is now working, and thank you for the kind words. I am going to close this issue as it appears to be resolved.

**Closed by volks73** 2021-01-02 16:10 UTC
Labels: bug, duplicate
